# Generated by Django 5.0.4 on 2024-04-21 16:39

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('second_name', models.CharField(max_length=30)),
                ('date', models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2006, 4, 26))])),
                ('adress', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('second_name', models.CharField(max_length=30)),
                ('date', models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2006, 4, 26))])),
                ('adress', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('setting_date', models.DateField()),
                ('status', models.CharField(max_length=10)),
                ('clients', models.ManyToManyField(to='medicalCenter_app.client')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalCenter_app.doctor')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalCenter_app.doctorspecialization'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('specialization_required', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalCenter_app.doctorspecialization')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('date', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date.today)])),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalCenter_app.client')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalCenter_app.doctor')),
                ('services', models.ManyToManyField(to='medicalCenter_app.service')),
            ],
        ),
    ]
