# Generated by Django 5.0.4 on 2024-04-21 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalCenter_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='clients',
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicalCenter_app.client'),
        ),
    ]
