# Generated by Django 5.0.4 on 2024-04-23 15:32

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalCenter_app', '0004_remove_client_date_remove_doctor_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birth_date',
            field=models.DateField(null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2006, 4, 28))]),
        ),
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(default='default_avatar.png', upload_to='imgs/avatars'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='birth_date',
            field=models.DateField(null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2006, 4, 28))]),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(default='default_avatar.png', upload_to='imgs/avatars'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='news',
            name='header',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default='no_img.png', upload_to='imgs/news_imgs'),
        ),
    ]
