# Generated by Django 5.0.4 on 2024-04-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalCenter_app', '0006_alter_client_birth_date_alter_doctor_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
