# Generated by Django 5.0.4 on 2024-04-25 19:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalCenter_app', '0008_alter_client_birth_date_alter_doctor_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Некорректный номер телефона', regex='^\\+375(44|29)\\d{7}$')]),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone_number',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Некорректный номер телефона', regex='^\\+375(44|29)\\d{7}$')]),
        ),
    ]
