# Generated by Django 5.0.4 on 2024-04-29 19:18

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalCenter_app', '0009_alter_client_phone_number_alter_doctor_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='services',
        ),
        migrations.AlterField(
            model_name='client',
            name='birth_date',
            field=models.DateField(null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2006, 5, 4), message='Вам должно быть не менее 18 лет для регистрации')]),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='birth_date',
            field=models.DateField(null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2006, 5, 4), message='Вам должно быть не менее 18 лет для регистрации')]),
        ),
        migrations.AddField(
            model_name='appointment',
            name='services',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicalCenter_app.service'),
        ),
    ]
