# Generated by Django 5.0.4 on 2024-04-29 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalCenter_app', '0010_appointment_time_remove_appointment_services_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='services',
            new_name='service',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicalCenter_app.client'),
        ),
    ]
