# Generated by Django 5.0.4 on 2024-04-30 16:52

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalCenter_app', '0011_rename_services_appointment_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='client',
            field=models.ManyToManyField(to='medicalCenter_app.client'),
        ),
        migrations.AlterField(
            model_name='client',
            name='birth_date',
            field=models.DateField(null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2006, 5, 5), message='Вам должно быть не менее 18 лет для регистрации')]),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='birth_date',
            field=models.DateField(null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2006, 5, 5), message='Вам должно быть не менее 18 лет для регистрации')]),
        ),
    ]
