# Generated by Django 5.0.4 on 2024-04-30 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalCenter_app', '0012_doctor_client_alter_client_birth_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='client',
            new_name='clients',
        ),
    ]
