# Generated by Django 5.0.4 on 2024-05-01 11:50

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalCenter_app', '0013_rename_client_doctor_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default='baseemail@mail.ru', max_length=30),
        ),
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.EmailField(default='baseemail@mail.ru', max_length=30),
        ),
        migrations.AlterField(
            model_name='client',
            name='birth_date',
            field=models.DateField(null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2006, 5, 6), message='Вам должно быть не менее 18 лет для регистрации')]),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='birth_date',
            field=models.DateField(null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2006, 5, 6), message='Вам должно быть не менее 18 лет для регистрации')]),
        ),
    ]
