# Generated by Django 5.0.4 on 2024-05-01 12:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalCenter_app', '0015_appointment_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='sender',
        ),
        migrations.AlterField(
            model_name='review',
            name='mark',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5, message='Значение должно быть от 1 до 5'), django.core.validators.MinValueValidator(1, message='Значение должно быть от 1 до 5')]),
        ),
    ]
