# Generated by Django 5.0.4 on 2024-05-01 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalCenter_app', '0016_remove_review_sender_alter_review_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicalCenter_app.client'),
        ),
    ]
