# Generated by Django 5.0.4 on 2024-05-01 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalCenter_app', '0019_client_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicalCenter_app.doctor'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='setting_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
