# Generated by Django 5.0.4 on 2024-05-01 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalCenter_app', '0020_alter_diagnosis_doctor_alter_diagnosis_setting_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='status',
        ),
    ]
