# Generated by Django 5.0.4 on 2024-05-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalCenter_app', '0022_remove_news_content_remove_news_header_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image_url',
            field=models.URLField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.URLField(default='', max_length=1000),
        ),
    ]
