# Generated by Django 5.0.4 on 2024-05-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalCenter_app', '0023_news_image_url_alter_news_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(null=True, upload_to='imgs/news_imgs'),
        ),
    ]
