# Generated by Django 5.0.4 on 2024-05-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalCenter_app', '0024_alter_news_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default='no_img.png', upload_to='imgs/news_imgs'),
        ),
    ]
