# Generated by Django 5.0.4 on 2024-05-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalCenter_app', '0025_remove_news_image_url_alter_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image_url',
            field=models.URLField(default='', max_length=1000),
        ),
    ]
