# Generated by Django 5.0.4 on 2024-05-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalCenter_app', '0027_alter_news_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='clients',
            field=models.ManyToManyField(blank=True, to='medicalCenter_app.client'),
        ),
    ]
