# Generated by Django 5.0.4 on 2024-05-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalCenter_app', '0028_alter_doctor_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='text',
            field=models.CharField(max_length=2000),
        ),
    ]
