# Generated by Django 5.0.4 on 2024-05-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalCenter_app', '0029_alter_about_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='about',
            name='text',
        ),
        migrations.AddField(
            model_name='about',
            name='end',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='about',
            name='start',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='about',
            name='advantages',
            field=models.ManyToManyField(to='medicalCenter_app.advantage'),
        ),
    ]
