# Generated by Django 5.0.4 on 2024-05-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalCenter_app', '0030_advantage_remove_about_text_about_end_about_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupons',
            name='coupon',
        ),
        migrations.AddField(
            model_name='coupons',
            name='name',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
