# Generated by Django 5.0.4 on 2024-05-03 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalCenter_app', '0032_alter_coupons_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupons',
            name='description',
        ),
    ]
