# Generated by Django 5.0.4 on 2024-05-04 07:49

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalCenter_app', '0034_coupons_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_starts', models.TimeField()),
                ('work_ends', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='temp',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='birth_date',
            field=models.DateField(null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2006, 5, 9), message='Вам должно быть не менее 18 лет для регистрации')]),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='birth_date',
            field=models.DateField(null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2006, 5, 9), message='Вам должно быть не менее 18 лет для регистрации')]),
        ),
        migrations.AddField(
            model_name='doctor',
            name='shcedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='medicalCenter_app.schedule'),
        ),
    ]
