# Generated by Django 5.0.4 on 2024-09-07 18:05

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalCenter_app', '0037_remove_appointment_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='logo',
            field=models.ImageField(default='MC_Logo.jpg', upload_to='imgs'),
        ),
        migrations.AlterField(
            model_name='client',
            name='birth_date',
            field=models.DateField(null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2006, 9, 12), message='Вам должно быть не менее 18 лет для регистрации')]),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='birth_date',
            field=models.DateField(null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2006, 9, 12), message='Вам должно быть не менее 18 лет для регистрации')]),
        ),
    ]
