# Generated by Django 5.0.4 on 2024-09-16 19:36

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalCenter_app', '0038_about_logo_alter_client_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='client',
            name='birth_date',
            field=models.DateField(null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2006, 9, 21), message='Вам должно быть не менее 18 лет для регистрации')]),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='birth_date',
            field=models.DateField(null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2006, 9, 21), message='Вам должно быть не менее 18 лет для регистрации')]),
        ),
    ]
