# Generated by Django 5.0.4 on 2024-09-16 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalCenter_app', '0039_appointment_count_alter_client_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
