# Generated by Django 5.0.4 on 2024-09-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalCenter_app', '0040_term_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='term',
            name='term',
            field=models.CharField(max_length=200),
        ),
    ]
