# Generated by Django 5.0.4 on 2024-09-18 17:05

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalCenter_app', '0041_alter_term_description_alter_term_term'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='news',
            name='url',
        ),
        migrations.AddField(
            model_name='news',
            name='content',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='client',
            name='birth_date',
            field=models.DateField(null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2006, 9, 23), message='Вам должно быть не менее 18 лет для регистрации')]),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='birth_date',
            field=models.DateField(null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2006, 9, 23), message='Вам должно быть не менее 18 лет для регистрации')]),
        ),
    ]
