# Generated by Django 5.0.4 on 2024-09-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalCenter_app', '0042_remove_news_image_url_remove_news_url_news_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
        migrations.AddField(
            model_name='news',
            name='url',
            field=models.URLField(default='', max_length=1000),
        ),
    ]
